# Generated by Django 6.0.6 on 2026-07-11 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='ddescription',
            new_name='description',
        ),
    ]
